# Collision Data Preparation

This notebook prepares the official UK Department for Transport collision dataset.

Objectives:

- Load the collision dataset
- Explore its structure
- Assess data quality
- Handle missing values
- Correct data types where necessary
- Save a cleaned version for further processing

Import Libraries

In [84]:
import pandas as pd
import numpy as np
from pathlib import Path

Load Dataset

In [85]:
DATA_PATH = Path('../data/raw')

df = pd.read_csv(DATA_PATH / '/content/drive/MyDrive/PROYECT_1/dft-road-casualty-statistics-collision-1979-latest-published-year.csv')

Filter Recent Records

The original dataset contains collision records from 1979 onwards.

To develop a model that better represents current road conditions, legislation and vehicle technologies, only collisions from **2010 onwards** are retained.

This still provides a large number of observations while improving the relevance of the training data.

In [86]:
pd.set_option('display.max_columns', None)

In [87]:
df = df[df['collision_year']>=2010].copy()

Exploration and Data Cleaning

In [88]:
df.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,local_authority_highway_current,first_road_class,first_road_number,road_type,speed_limit,junction_detail_historic,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control_historic,pedestrian_crossing_physical_facilities_historic,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,2018450290294,2018,450290294,487906.0,132932.0,-0.746206,51.088970,45,3,2,2,15/04/2018,1,08:00,517,E07000216,E10000030,E10000030,6,0,6,30.0,0,0,-1,0,-1,0,0,0,1,9,1,0,0,0,1,2,2,E01030927,3,1,0.000000,1.000000
1,2020230984311,2020,230984311,433493.0,258232.0,-1.511123,52.221299,23,2,5,2,21/09/2020,2,23:00,293,E07000221,E10000031,E10000031,1,40,3,70.0,0,0,-1,0,-1,0,0,0,6,1,1,4,0,13,2,1,1,E01031199,6,1,1.000000,0.000000
5,2019010177739,2019,010177739,536988.0,176455.0,-0.029082,51.470486,1,3,2,1,29/04/2019,2,09:01,7,E09000023,E09000023,E09000023,3,20,6,20.0,9,19,4,6,0,0,4,14,1,1,1,0,0,0,1,1,2,E01003210,-1,0,0.000000,1.000000
10,2011370225611,2011,370225611,654970.0,293400.0,1.753436,52.478868,37,3,2,1,05/06/2011,1,13:05,416,E07000206,E10000029,E10000029,6,0,6,20.0,3,13,4,6,0,0,0,0,1,1,1,0,0,0,1,1,2,E01030249,-1,0,0.057667,0.942333
12,2013471300464,2013,471300464,527289.0,136778.0,-0.182787,51.116101,47,3,1,1,23/01/2013,4,11:00,560,E07000226,E10000032,E10000032,3,2004,3,30.0,1,0,2,6,0,0,4,14,1,1,2,0,0,0,1,1,2,E01031585,-1,0,0.000000,1.000000

In [89]:
df.shape

(1886746, 44)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1886746 entries, 0 to 9014547
Data columns (total 44 columns):
 #   Column                                            Dtype
---  ------                                            -----
 0   collision_index                                   object
 1   collision_year                                    int64
 2   collision_ref_no                                  object
 3   location_easting_osgr                             float64
 4   location_northing_osgr                            float64
 5   longitude                                         float64
 6   latitude                                          float64
 7   police_force                                      int64
 8   collision_severity                                int64
 9   number_of_vehicles                                int64
 10  number_of_casualties                              int64
 11  date                                              object
 12  day_of_week                                       int64
 13  time                                              object
 14  local_authority_district                          int64
 15  local_authority_ons_district                      object
 16  local_authority_highway                           object
 17  local_authority_highway_current                   object
 18  first_road_class                                  int64
 19  first_road_number                                 int64
 20  road_type                                         int64
 21  speed_limit                                       float64
 22  junction_detail_historic                          int64
 23  junction_detail                                   int64
 24  junction_control                                  int64
 25  second_road_class                                 int64
 26  second_road_number                                int64
 27  pedestrian_crossing_human_control_historic        int64
 28  pedestrian_crossing_physical_facilities_historic  int64
 29  pedestrian_crossing                               int64
 30  light_conditions                                  int64
 31  weather_conditions                                int64
 32  road_surface_conditions                           int64
 33  special_conditions_at_site                        int64
 34  carriageway_hazards_historic                      int64
 35  carriageway_hazards                               int64
 36  urban_or_rural_area                               int64
 37  did_police_officer_attend_scene_of_accident       int64
 38  trunk_road_flag                                   int64
 39  lsoa_of_accident_location                         object
 40  enhanced_severity_collision                       int64
 41  collision_injury_based                            int64
 42  collision_adjusted_severity_serious               float64
 43  collision_adjusted_severity_slight                float64
dtypes: float64(7), int64(29), object(8)
memory usage: 647.8+ MB

In [91]:
df.columns

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'collision_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'local_authority_highway_current',
       'first_road_class', 'first_road_number', 'road_type', 'speed_limit',
       'junction_detail_historic', 'junction_detail', 'junction_control',
       'second_road_class', 'second_road_number',
       'pedestrian_crossing_human_control_historic',
       'pedestrian_crossing_physical_facilities_historic',
       'pedestrian_crossing', 'light_conditions', 'weather_conditions',
       'road_surface_conditions', 'special_conditions_at_site',
       'carriageway_hazards_historic', 'carriageway_hazards',
       'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident',
       'trunk_road_flag', 'lsoa_of_accident_location',
       'enhanced_severity_collision', 'collision_injury_based',
       'collision_adjusted_severity_serious',
       'collision_adjusted_severity_slight'],
      dtype='object')

In [92]:
df.describe()

,collision_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,day_of_week,local_authority_district,first_road_class,first_road_number,road_type,speed_limit,junction_detail_historic,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control_historic,pedestrian_crossing_physical_facilities_historic,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
count,1.886746e+06,1.886545e+06,1.886545e+06,1.886545e+06,1.886545e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886709e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06
mean,2.016348e+03,4.489366e+05,2.862676e+05,-1.300337e+00,5.246391e+01,2.916419e+01,2.803487e+00,1.832587e+00,1.314067e+00,4.116988e+00,2.657407e+02,4.148602e+00,8.058242e+02,5.198619e+00,3.749886e+01,2.874606e+00,6.907432e+00,1.780486e+00,3.133598e+00,2.279541e+02,1.253089e-01,9.187013e-01,3.928821e+00,1.980917e+00,1.594747e+00,1.361623e+00,1.423610e-01,1.029614e-01,1.308200e+00,1.337305e+00,1.295016e+00,1.653465e+00,1.606470e-01,2.439496e-01,2.132975e-01,7.738560e-01
std,4.274201e+00,9.472039e+04,1.550009e+05,1.389491e+00,1.396045e+00,2.503738e+01,4.284728e-01,7.046588e-01,7.781080e-01,1.924024e+00,2.687767e+02,1.445891e+00,1.609095e+03,1.670380e+00,1.407693e+01,8.304810e+00,7.382331e+00,2.428532e+00,2.755563e+00,9.486965e+02,1.154512e+00,2.164611e+00,1.157150e+01,1.678254e+00,1.715293e+00,8.231699e-01,1.101660e+00,1.004069e+00,8.789282e+00,4.729997e-01,5.574166e-01,8.835930e-01,2.178901e+00,4.294628e-01,3.625177e-01,3.723175e-01
min,2.010000e+03,6.408400e+04,1.021100e+04,-7.525273e+00,4.991221e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00,1.000000e+00,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.013000e+03,3.858040e+05,1.761700e+05,-2.213248e+00,5.147213e+01,6.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,6.000000e+00,3.000000e+00,0.000000e+00,6.000000e+00,3.000000e+01,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,8.410091e-01
50%,2.016000e+03,4.541500e+05,2.337750e+05,-1.200037e+00,5.198953e+01,3.000000e+01,3.000000e+00,2.000000e+00,1.000000e+00,4.000000e+00,2.040000e+02,4.000000e+00,3.800000e+01,6.000000e+00,3.000000e+01,1.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,-1.000000e+00,0.000000e+00,4.187391e-02,9.544244e-01
75%,2.020000e+03,5.277810e+05,3.897360e+05,-1.584600e-01,5.340163e+01,4.500000e+01,3.000000e+00,2.000000e+00,1.000000e+00,6.000000e+00,4.760000e+02,6.000000e+00,5.720000e+02,6.000000e+00,4.000000e+01,3.000000e+00,1.300000e+01,4.000000e+00,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,1.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,-1.000000e+00,0.000000e+00,1.479813e-01,1.000000e+00
max,2.024000e+03,6.553910e+05,1.209512e+06,1.759829e+00,6.076372e+01,9.900000e+01,3.000000e+00,6.700000e+01,9.300000e+01,7.000000e+00,9.410000e+02,6.000000e+00,9.999000e+03,9.000000e+00,7.000000e+01,9.900000e+01,9.900000e+01,9.000000e+00,9.000000e+00,9.999000e+03,9.000000e+00,9.000000e+00,9.900000e+01,7.000000e+00,9.000000e+00,9.000000e+00,9.000000e+00,9.000000e+00,9.900000e+01,3.000000e+00,3.000000e+00,2.000000e+00,7.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [93]:
df.isnull().sum()

collision_index                                       0
collision_year                                        0
collision_ref_no                                      0
location_easting_osgr                               201
location_northing_osgr                              201
longitude                                           201
latitude                                            201
police_force                                          0
collision_severity                                    0
number_of_vehicles                                    0
number_of_casualties                                  0
date                                                  0
day_of_week                                           0
time                                                  0
local_authority_district                              0
local_authority_ons_district                          0
local_authority_highway                               0
local_authority_highway_current                     287
first_road_class                                      0
first_road_number                                     0
road_type                                             0
speed_limit                                          37
junction_detail_historic                              0
junction_detail                                       0
junction_control                                      0
second_road_class                                     0
second_road_number                                    0
pedestrian_crossing_human_control_historic            0
pedestrian_crossing_physical_facilities_historic      0
pedestrian_crossing                                   0
light_conditions                                      0
weather_conditions                                    0
road_surface_conditions                               0
special_conditions_at_site                            0
carriageway_hazards_historic                          0
carriageway_hazards                                   0
urban_or_rural_area                                   0
did_police_officer_attend_scene_of_accident           0
trunk_road_flag                                       0
lsoa_of_accident_location                             0
enhanced_severity_collision                           0
collision_injury_based                                0
collision_adjusted_severity_serious                   0
collision_adjusted_severity_slight                    0
dtype: int64

In [94]:
((df.isnull().sum() / len(df)) * 100).sort_values(ascending=False).map("{:.2f}%".format)

local_authority_highway_current                     0.02%
location_easting_osgr                               0.01%
longitude                                           0.01%
latitude                                            0.01%
location_northing_osgr                              0.01%
speed_limit                                         0.00%
collision_ref_no                                    0.00%
collision_year                                      0.00%
collision_severity                                  0.00%
number_of_vehicles                                  0.00%
collision_index                                     0.00%
police_force                                        0.00%
date                                                0.00%
number_of_casualties                                0.00%
local_authority_district                            0.00%
day_of_week                                         0.00%
local_authority_ons_district                        0.00%
local_authority_highway                             0.00%
first_road_class                                    0.00%
time                                                0.00%
first_road_number                                   0.00%
road_type                                           0.00%
junction_detail_historic                            0.00%
junction_detail                                     0.00%
junction_control                                    0.00%
second_road_class                                   0.00%
second_road_number                                  0.00%
pedestrian_crossing_human_control_historic          0.00%
pedestrian_crossing_physical_facilities_historic    0.00%
pedestrian_crossing                                 0.00%
light_conditions                                    0.00%
weather_conditions                                  0.00%
road_surface_conditions                             0.00%
special_conditions_at_site                          0.00%
carriageway_hazards_historic                        0.00%
carriageway_hazards                                 0.00%
urban_or_rural_area                                 0.00%
did_police_officer_attend_scene_of_accident         0.00%
trunk_road_flag                                     0.00%
lsoa_of_accident_location                           0.00%
enhanced_severity_collision                         0.00%
collision_injury_based                              0.00%
collision_adjusted_severity_serious                 0.00%
collision_adjusted_severity_slight                  0.00%
dtype: object

In [95]:
df.duplicated().sum()

np.int64(0)

In [96]:
df.nunique().sort_values()

collision_injury_based                                    2
collision_severity                                        3
trunk_road_flag                                           3
did_police_officer_attend_scene_of_accident               4
urban_or_rural_area                                       4
pedestrian_crossing_human_control_historic                5
first_road_class                                          6
light_conditions                                          6
enhanced_severity_collision                               6
road_type                                                 7
road_surface_conditions                                   7
day_of_week                                               7
junction_control                                          7
carriageway_hazards_historic                              8
junction_detail                                           8
pedestrian_crossing_physical_facilities_historic          8
second_road_class                                         9
special_conditions_at_site                               10
pedestrian_crossing                                      10
speed_limit                                              10
weather_conditions                                       10
junction_detail_historic                                 11
carriageway_hazards                                      14
collision_year                                           15
number_of_vehicles                                       28
number_of_casualties                                     47
police_force                                             52
local_authority_highway_current                         207
local_authority_highway                                 213
local_authority_district                                382
local_authority_ons_district                            393
time                                                   1440
second_road_number                                     3783
first_road_number                                      3946
date                                                   5479
lsoa_of_accident_location                             37118
location_easting_osgr                                366649
location_northing_osgr                               451929
collision_adjusted_severity_serious                  993441
collision_adjusted_severity_slight                   993441
latitude                                            1309200
longitude                                           1425969
collision_ref_no                                    1655485
collision_index                                     1886746
dtype: int64

In [97]:
df['speed_limit'] = df['speed_limit'].fillna(df['speed_limit'].mode()[0])

In [98]:
df['speed_limit'].isnull().sum()

np.int64(0)

In [99]:
df[
    [
        "collision_severity",
        "enhanced_severity_collision",
        "collision_injury_based",
        "collision_adjusted_severity_serious",
        "collision_adjusted_severity_slight"
    ]
].head(10)

,collision_severity,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,3,3,1,0.000000,1.000000
1,2,6,1,1.000000,0.000000
5,3,-1,0,0.000000,1.000000
10,3,-1,0,0.057667,0.942333
12,3,-1,0,0.000000,1.000000
13,2,-1,0,1.000000,0.000000
14,3,-1,0,0.128429,0.871571
15,3,3,1,0.000000,1.000000
18,2,7,1,1.000000,0.000000
19,3,3,1,0.000000,1.000000

In [100]:
df[
    [
        "collision_severity",
        "enhanced_severity_collision",
        "collision_injury_based",
        "collision_adjusted_severity_serious",
        "collision_adjusted_severity_slight"
    ]
].describe()

,collision_severity,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
count,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06,1.886746e+06
mean,2.803487e+00,1.606470e-01,2.439496e-01,2.132975e-01,7.738560e-01
std,4.284728e-01,2.178901e+00,4.294628e-01,3.625177e-01,3.723175e-01
min,1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,8.410091e-01
50%,3.000000e+00,-1.000000e+00,0.000000e+00,4.187391e-02,9.544244e-01
75%,3.000000e+00,-1.000000e+00,0.000000e+00,1.479813e-01,1.000000e+00
max,3.000000e+00,7.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [101]:
df.drop(["enhanced_severity_collision",
        "collision_injury_based",
        "collision_adjusted_severity_serious",
        "collision_adjusted_severity_slight"], axis=1, inplace=True)

In [102]:
df.drop('collision_ref_no',axis=1,inplace=True)

In [103]:
df.head()

,collision_index,collision_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,local_authority_highway_current,first_road_class,first_road_number,road_type,speed_limit,junction_detail_historic,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing_human_control_historic,pedestrian_crossing_physical_facilities_historic,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,2018450290294,2018,487906.0,132932.0,-0.746206,51.088970,45,3,2,2,15/04/2018,1,08:00,517,E07000216,E10000030,E10000030,6,0,6,30.0,0,0,-1,0,-1,0,0,0,1,9,1,0,0,0,1,2,2,E01030927
1,2020230984311,2020,433493.0,258232.0,-1.511123,52.221299,23,2,5,2,21/09/2020,2,23:00,293,E07000221,E10000031,E10000031,1,40,3,70.0,0,0,-1,0,-1,0,0,0,6,1,1,4,0,13,2,1,1,E01031199
5,2019010177739,2019,536988.0,176455.0,-0.029082,51.470486,1,3,2,1,29/04/2019,2,09:01,7,E09000023,E09000023,E09000023,3,20,6,20.0,9,19,4,6,0,0,4,14,1,1,1,0,0,0,1,1,2,E01003210
10,2011370225611,2011,654970.0,293400.0,1.753436,52.478868,37,3,2,1,05/06/2011,1,13:05,416,E07000206,E10000029,E10000029,6,0,6,20.0,3,13,4,6,0,0,0,0,1,1,1,0,0,0,1,1,2,E01030249
12,2013471300464,2013,527289.0,136778.0,-0.182787,51.116101,47,3,1,1,23/01/2013,4,11:00,560,E07000226,E10000032,E10000032,3,2004,3,30.0,1,0,2,6,0,0,4,14,1,1,2,0,0,0,1,1,2,E01031585

In [104]:
historic_columns = [
    ("junction_detail_historic", "junction_detail"),
    ("pedestrian_crossing_human_control_historic", "pedestrian_crossing"),
    ("pedestrian_crossing_physical_facilities_historic", "pedestrian_crossing"),
    ("carriageway_hazards_historic", "carriageway_hazards")
]

In [105]:
for old_col, new_col in historic_columns:
  print('-' * 50)
  print(f'{old_col}')
  print(df[old_col].value_counts(dropna=False).sort_index())
  print()
  print(f'{new_col}')
  print(df[new_col].value_counts(dropna=False).sort_index())
  print()

--------------------------------------------------
junction_detail_historic
junction_detail_historic
-1      59621
 0     735304
 1     154165
 2      23962
 3     557863
 5      25217
 6     176252
 7      21873
 8      56415
 9      63464
 99     12610
Name: count, dtype: int64

junction_detail
junction_detail
-1      17684
 0     967476
 13    572184
 16    181409
 17     22675
 18     57359
 19     67957
 99         2
Name: count, dtype: int64

--------------------------------------------------
pedestrian_crossing_human_control_historic
pedestrian_crossing_human_control_historic
-1      63920
 0    1774567
 1       5675
 2      12655
 9      29929
Name: count, dtype: int64

pedestrian_crossing
pedestrian_crossing
-1        5477
 0     1489758
 11       5852
 12      13109
 13      62597
 14     103106
 15     137649
 16       5002
 17      43426
 99      20770
Name: count, dtype: int64

--------------------------------------------------
pedestrian_crossing_physical_facilities_historic
pedestrian_crossing_physical_facilities_historic
-1      63830
 0    1440525
 1      63806
 4     104419
 5     139796
 7       4974
 8      42658
 9      26738
Name: count, dtype: int64

pedestrian_crossing
pedestrian_crossing
-1        5477
 0     1489758
 11       5852
 12      13109
 13      62597
 14     103106
 15     137649
 16       5002
 17      43426
 99      20770
Name: count, dtype: int64

--------------------------------------------------
carriageway_hazards_historic
carriageway_hazards_historic
-1      64360
 0    1774238
 1       3041
 2      15045
 3       2829
 6       4235
 7       7694
 9      15304
Name: count, dtype: int64

carriageway_hazards
carriageway_hazards
-1        5199
 0     1794151
 11       4848
 12       2768
 13      21342
 14       4307
 15       5120
 16       2865
 17      13589
 18       2776
 19       4189
 20       7721
 21       4586
 99      13285
Name: count, dtype: int64

In [106]:
df.drop(['junction_detail_historic', 'pedestrian_crossing_human_control_historic',
'pedestrian_crossing_physical_facilities_historic', 'carriageway_hazards_historic'],axis=1,inplace=True)

Save Clean Dataset

Export the cleaned dataset.

The resulting dataset will be used during the data integration stage together with the vehicle and casualty datasets.

In [107]:
df.to_csv('/content/drive/MyDrive/PROYECT_1/collision_clean.csv', index=False)

Final Dataset

The collision dataset was successfully prepared for the next stage of the project.

Summary of the work completed:

- Filtered the dataset to include collisions from 2010 onwards.
- Assessed the overall quality of the data.
- Verified that no duplicate records were present.
- Analysed missing values.
- Removed redundant identifier variables.
- Removed historical variables replaced by newer standards.
- Removed variables that could introduce data leakage into the machine learning model.
- Imputed missing values where appropriate.
- Exported a clean dataset ready for data integration.

In [108]:
print('Collision Dataset Summary')
print('='*50)
print(f'Rows: {df.shape[0]}')
print(f'Columns: {df.shape[1]}')
print(f'Missing Values: {df.isnull().sum().sum()}')
print(f'Duplicate Rows: {df.duplicated().sum()}')

Collision Dataset Summary
==================================================
Rows: 1886746
Columns: 35
Missing Values: 1091
Duplicate Rows: 0

In [109]:
df.head()

,collision_index,collision_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,local_authority_district,local_authority_ons_district,local_authority_highway,local_authority_highway_current,first_road_class,first_road_number,road_type,speed_limit,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,2018450290294,2018,487906.0,132932.0,-0.746206,51.088970,45,3,2,2,15/04/2018,1,08:00,517,E07000216,E10000030,E10000030,6,0,6,30.0,0,-1,0,-1,0,1,9,1,0,0,1,2,2,E01030927
1,2020230984311,2020,433493.0,258232.0,-1.511123,52.221299,23,2,5,2,21/09/2020,2,23:00,293,E07000221,E10000031,E10000031,1,40,3,70.0,0,-1,0,-1,0,6,1,1,4,13,2,1,1,E01031199
5,2019010177739,2019,536988.0,176455.0,-0.029082,51.470486,1,3,2,1,29/04/2019,2,09:01,7,E09000023,E09000023,E09000023,3,20,6,20.0,19,4,6,0,14,1,1,1,0,0,1,1,2,E01003210
10,2011370225611,2011,654970.0,293400.0,1.753436,52.478868,37,3,2,1,05/06/2011,1,13:05,416,E07000206,E10000029,E10000029,6,0,6,20.0,13,4,6,0,0,1,1,1,0,0,1,1,2,E01030249
12,2013471300464,2013,527289.0,136778.0,-0.182787,51.116101,47,3,1,1,23/01/2013,4,11:00,560,E07000226,E10000032,E10000032,3,2004,3,30.0,0,2,6,0,14,1,1,2,0,0,1,1,2,E01031585